# Generated by Django 4.0.1 on 2022-01-21 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=80)),
                ('price', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=25)),
                ('question_text', models.TextField()),
                ('answer_first', models.CharField(max_length=20)),
                ('answer_last', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Apartment_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_value', models.CharField(max_length=50)),
                ('expert_score', models.FloatField()),
                ('apartment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selectionApartments.apartment')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selectionApartments.question')),
            ],
        ),
    ]
