# Generated by Django 4.0.1 on 2022-01-21 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selectionApartments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment_question',
            old_name='apartment_id',
            new_name='apartment',
        ),
        migrations.RenameField(
            model_name='apartment_question',
            old_name='question_id',
            new_name='question',
        ),
    ]
